version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "3000:3000"
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

  db:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    environment:
      - JAVA_OPTS=-Xmx512m
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data: